db.mensajes.insertMany(
    [
        {
            id:1,
            email:"hans@gmail.com",
            mensaje:"Hola",
            fecha:Date.now()
        },
        {
            id:2,
            email:"jose@gmail.com",
            mensaje:"Hola",
            fecha:Date.now()
        },
        {
            id:3,
            email:"hans@gmail.com",
            mensaje:"¿Como estas?",
            fecha:Date.now()
        },
        {
            id:4,
            email:"jose@gmail.com",
            mensaje:"Triste",
            fecha:Date.now()
        },
        {
            id:5,
            email:"hans@gmail.com",
            mensaje:"No quiero verte triste, vete por favor",
            fecha:Date.now()
        },
        {
            id:6,
            email:"jose@gmail.com",
            mensaje:"a",
            fecha:Date.now()
        },
        {
            id:7,
            email:"luis@gmail.com",
            mensaje:"¿por que estas triste?",
            fecha:Date.now()
        },
        {
            id:8,
            email:"jose@gmail.com",
            mensaje:"no se",
            fecha:Date.now()
        },
        {
            id:9,
            email:"luis@gmail.com",
            mensaje:"a",
            fecha:Date.now()
        },
        {
            id:10,
            email:"hans@gmail.com",
            mensaje:"¿Como estas luis?",
            fecha:Date.now()
        },
        {
            id:11,
            email:"luis@gmail.com",
            mensaje:"estoy bien",
            fecha:Date.now()
        },
        {
            id:12,
            email:"hans@gmail.com",
            mensaje:"a",
            fecha:Date.now()
        },
        {
            id:13,
            email:"luis@gmail.com",
            mensaje:"a",
            fecha:Date.now()
        },
        {
            id:14,
            email:"jose@gmail.com",
            mensaje:"a",
            fecha:Date.now()
        },
        {
            id:15,
            email:"hans@gmail.com",
            mensaje:"Bueno ya me voy",
            fecha:Date.now()
        },
        {
            id:16,
            email:"jose@gmail.com",
            mensaje:"a",
            fecha:Date.now()
        },
        {
            id:17,
            email:"luis@gmail.com",
            mensaje:"a",
            fecha:Date.now()
        },
        {
            id:18,
            email:"hans@gmail.com",
            mensaje:"a",
            fecha:Date.now()
        },
        {
            id:19,
            email:"luis@gmail.com",
            mensaje:"adios",
            fecha:Date.now()
        },
        {
            id:20,
            email:"jose@gmail.com",
            mensaje:"adios",
            fecha:Date.now()
        },
    ]
)